name: Test

on:
  push:
    branches:
      - "main"

jobs:
 run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
          cache: pip
          cache-dependency-path: ".github/workflows/tests.yml"
      - name: setup
        run: |
          python --version
          python -m pip install --upgrade pip
      - name: install
        run: |
          pip install pytest
      - name: test
        run: |
          pytest test/test.py
